services:
  name: try
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  disk:
    name: data
    mountPath: /data
  region: oregon                                      # optional (defaults to oregon)
  plan: standard                                      # optional
  branch: master                                      # optional (uses repo default)
  dockerCommand: ./start.sh                          # optional (defaults to Dockerfile command)
